language: python
cache: pip
notifications:
  email: false
sudo: true

python:
- 3.6.6

install:
- pip install -r requirements.txt

jobs:
  include:

  - name: "Unit Tests"
    python: 3.7
  script: ./manage.py test
