language: python
cache: pip
notifications:
  email: false
sudo: true

python:
- 3.6.6

install:
- pip install -r requirements.txt

env:
- DJANGO_SETTINGS_MODULE=SnapCal2.settings
- GOOGLE_APPLICATION_CREDENTIALS=./creds.json

script: python manage.py test
